exclude:         [".gitignore", "Gruntfile.js", "package.json", "node_modules", "README.md", "less"]

# Custom vars
current_version: 2.1.1

download_dist:   https://github.com/Zweer/zwe-less/archive/master.zip